## Importación de librerías

In [1]:
!pip install pandas openpyxl

Requirement already satisfied: pandas in c:\users\troya\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: openpyxl in c:\users\troya\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\troya\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\troya\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\troya\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\troya\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\troya\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\troya\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

## Carga de datos y leer todas las hojas del archivo Excel

In [2]:
import pandas as pd

# Ruta del archivo Excel
archivo_excel = '../data/raw/customer-details.xlsx'

# Leer todas las hojas en un diccionario
hojas = pd.read_excel(archivo_excel, sheet_name=None)

# Ver los nombres de las hojas
print("Hojas encontradas:", hojas.keys())

Hojas encontradas: dict_keys(['2012', '2013', '2014'])

## Guardar cada hoja en su propio DataFrame

In [3]:
df_2012 = hojas['2012']
df_2013 = hojas['2013']
df_2014 = hojas['2014']

## Vamos a empezar limpiar la hoja de 2012

In [4]:
df_2012.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

## Selección de columnas

Vamos a eliminar la columna de `Unnamed: 0` ya que no nos aporta nada de información. Se trata de un índice antiguo que se guardó por error al exportar el Excel. No tiene valor analítico y puede eliminarse sin problema.

## Eliminar duplicados y nulos

No hay duplicados ni nulos en el dataset.

## Eliminación de de la columna `Unnamed: 0`

In [8]:
df_2012 = df_2012.drop_duplicates()

In [9]:
columnas_eliminar = [
    'Unnamed: 0'
    ]

In [10]:
df_2012.drop(columns=columnas_eliminar)

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb
...,...,...,...,...,...,...
20110,114469,0,2,2012-10-28,13,25f35a3f-0fd2-4e6a-b4d5-74fa1a1f4cfc
20111,82207,0,1,2012-02-10,27,a3d2d088-3781-44ea-9944-a4a40df51285
20112,135009,0,0,2012-09-14,17,3769cb72-26be-40f2-9a93-f752fc96d628
20113,8486,1,1,2012-07-04,18,d507f6b3-a030-46d7-9615-61fe3f6b8028
20114,144419,1,0,2012-04-12,29,8299f0a6-e4c0-49fc-87ab-81308b70f80f

Ya hemos eliminado la columna `Unnamed: 0` de la hoja de 2012 del dataset, y cómo ya sabemos que no hay nulos ni duplicados en esta hoja, pasamos a la limpieza de la hoja del 2013.

## Limpieza hoja 2013

In [11]:
df_2013.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,82407,0,1,2013-10-07,29,ef81336c-e41a-46d0-8a30-5d4ac3b836be
1,1,24877,0,0,2013-04-21,32,50b224ac-84b4-42a7-aba9-3e1d1d620479
2,2,78839,1,0,2013-11-25,21,9cb15c53-b647-464a-add9-09cdae04897c
3,3,113859,1,1,2013-01-06,12,f8aaf334-949d-4943-a214-b64fe9c088b4
4,4,147317,0,0,2013-07-10,14,885fe85a-3718-4760-a32a-a57628cf7528

## Selección de columnas

Vamos a eliminar la columna de `Unnamed: 0` ya que no nos aporta nada de información. Se trata de un índice antiguo que se guardó por error al exportar el Excel. No tiene valor analítico y puede eliminarse sin problema.

## Eliminar duplicados y nulos

No hay duplicados ni nulos en el dataset.

## Eliminación de de la columna `Unnamed: 0`

In [12]:
df_2013 = df_2013.drop_duplicates()

In [13]:
columnas_eliminar = [
    'Unnamed: 0'
    ]

In [14]:
df_2013.drop(columns=columnas_eliminar)

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,82407,0,1,2013-10-07,29,ef81336c-e41a-46d0-8a30-5d4ac3b836be
1,24877,0,0,2013-04-21,32,50b224ac-84b4-42a7-aba9-3e1d1d620479
2,78839,1,0,2013-11-25,21,9cb15c53-b647-464a-add9-09cdae04897c
3,113859,1,1,2013-01-06,12,f8aaf334-949d-4943-a214-b64fe9c088b4
4,147317,0,0,2013-07-10,14,885fe85a-3718-4760-a32a-a57628cf7528
...,...,...,...,...,...,...
8960,139839,0,0,2013-12-10,8,6f7a03ac-c1b9-4acf-a28b-37cc8254a92e
8961,65516,0,2,2013-10-01,26,ed489dce-7ccf-46ad-a0d4-bb71c566fa40
8962,56664,1,0,2013-12-07,13,01b3ac53-b1bd-450a-be11-6893b3aeadd5
8963,25089,0,1,2013-08-24,14,8906c203-a13f-4b10-985c-bd72bd01a011
8964,77504,0,0,2013-06-30,6,ba7fb638-c6cb-4dc8-aad4-75456c3818c5

Ya hemos eliminado la columna `Unnamed: 0` de la hoja de 2013 del dataset, y cómo ya sabemos que no hay nulos ni duplicados en esta hoja, pasamos a la limpieza de la hoja del 2014.

## Limpieza hoja 2014

In [15]:
df_2014.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,168812,1,1,2014-06-10,27,4d6c811c-0f24-4a73-b374-2ebd1f80d46e
1,1,108615,2,1,2014-04-05,24,eef0f24f-cbdb-4c67-b371-09d7bc59695e
2,2,179041,0,2,2014-09-22,4,bbfdcedd-199d-4927-94bb-5dad051ff471
3,3,116639,2,2,2014-08-16,3,e8ebb67d-4ee1-4615-b701-eefe3af607eb
4,4,49537,0,1,2014-09-05,28,f7f79ace-0024-4505-a401-f340946f0942

## Selección de columnas

Vamos a eliminar la columna de `Unnamed: 0` ya que no nos aporta nada de información. Se trata de un índice antiguo que se guardó por error al exportar el Excel. No tiene valor analítico y puede eliminarse sin problema.

## Eliminar duplicados y nulos

No hay duplicados ni nulos en el dataset.

## Eliminación de de la columna `Unnamed: 0`

In [16]:
df_2014 = df_2014.drop_duplicates()

In [17]:
columnas_eliminar = [
    'Unnamed: 0'
    ]

In [18]:
df_2014.drop(columns=columnas_eliminar)

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,168812,1,1,2014-06-10,27,4d6c811c-0f24-4a73-b374-2ebd1f80d46e
1,108615,2,1,2014-04-05,24,eef0f24f-cbdb-4c67-b371-09d7bc59695e
2,179041,0,2,2014-09-22,4,bbfdcedd-199d-4927-94bb-5dad051ff471
3,116639,2,2,2014-08-16,3,e8ebb67d-4ee1-4615-b701-eefe3af607eb
4,49537,0,1,2014-09-05,28,f7f79ace-0024-4505-a401-f340946f0942
...,...,...,...,...,...,...
14085,156980,1,2,2014-05-17,7,5f432048-d515-4bb5-9c94-62db451f88d4
14086,139820,0,0,2014-09-29,1,993bbbd6-4dbc-4a40-a408-f91f8462bee6
14087,78470,2,2,2014-10-28,12,d6271666-319d-42c8-a741-cb22bf2c2093
14088,144218,0,1,2014-07-01,9,f67fbfa8-6573-414d-a805-b26a2f1b1ceb
14089,115155,0,2,2014-12-25,7,9727bc06-c11a-461a-a5bb-3d210467cc2a

Ya hemos eliminado la columna `Unnamed: 0` de la hoja de 2014 del dataset, y cómo ya sabemos que no hay nulos ni duplicados en esta hoja, damos por finalizada esta fase del proyecto.